### ISSUE TITLE
Running Panoptic Segmentation on cityscapes using the "mobilenet_v3_large_os32.textproto" config file provided #102

### ISSUE THREAD

**Issue by prabal27** [google-research/deeplab2#103]
### Tensorflow 2.6.0

Hello deeplab team,

**After running the following command:

**python trainer/train.py     --config_file=configs/cityscapes/panoptic_deeplab/mobilenet_v3_large_os32.textproto     --mode=train     --model_dir=Model_Output/     --num_gpus=1**

I get this error log.**

2022-06-10 12:24:53.117800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.149730: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.149850: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I0610 12:24:53.150171 139902151967936 train.py:65] Reading the config file.
I0610 12:24:53.152600 139902151967936 train.py:69] Starting the experiment.
2022-06-10 12:24:53.152945: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-10 12:24:53.154345: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.154446: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.154517: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.533613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.533731: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.533807: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-10 12:24:53.533883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 87 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
I0610 12:24:53.535348 139902151967936 train_lib.py:104] Using strategy <class 'tensorflow.python.distribute.one_device_strategy.OneDeviceStrategy'> with 1 replicas
I0610 12:24:53.540082 139902151967936 deeplab.py:57] Synchronized Batchnorm is used.
Traceback (most recent call last):
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/trainer/train.py", line 76, in <module>
    app.run(main)
  File "/home/prabal/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/prabal/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/trainer/train.py", line 71, in main
    train_lib.run_experiment(FLAGS.mode, config, combined_model_dir, FLAGS.master,
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/trainer/train_lib.py", line 127, in run_experiment
    deeplab_model = create_deeplab_model(
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/trainer/train_lib.py", line 57, in create_deeplab_model
    return deeplab.DeepLab(config, dataset_descriptor)
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/model/deeplab.py", line 77, in __init__
    self._encoder = builder.create_encoder(
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/model/builder.py", line 57, in create_encoder
    return create_mobilenet_encoder(
  File "/home/prabal/MachineLearning/MLAlgorithms/SemanticSegmentation/deeplab2/model/builder.py", line 87, in create_mobilenet_encoder
    assert backbone_options.use_squeeze_and_excite
AssertionError

**Comment by aquariusjay** [comment]
Hi @prabal27,

Thanks for the reporting the issue.
It seems that we forgot to include use_squeeze_and_excite in the config (same as this [line](https://github.com/google-research/deeplab2/blob/main/configs/cityscapes/panoptic_deeplab/mobilenet_v3_large_os16.textproto#L34)).
Could you please try adding `use_squeeze_and_excite: true` in the config?

Cheers,

**Comment by prabal27** [comment]
Thanks @aquariusjay! The training started after it but I am getting following warning:
I0614 17:19:46.944303 140015487653056 deeplab.py:57] Synchronized Batchnorm is used.
I0614 17:19:46.952933 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.956633 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.959629 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.975349 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.978267 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.981226 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:46.984198 140015487653056 blocks.py:175] Squeeze and Excitation is skipped due to undefined se_ratio
I0614 17:19:47.024570 140015487653056 deeplab.py:96] Setting pooling size to (24, 24)

Why the network is skipping the Squeeze and Excitation part? Do I need to add another parameter?

**Comment by prabal27** [comment]
Hi @aquariusjay,

Thank you so much for the help.
