### ISSUE TITLE
MOT-STEP transfer error

### ISSUE THREAD

**Issue by yjlin0223** [google-research/deeplab2#34]
2021-07-13 18:53:38.368250: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0713 18:53:39.327753 140106723893440 build_step_data.py:292] Starts to processing STEP dataset split train.
Traceback (most recent call last):
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/build_step_data.py", line 298, in <module>
    app.run(main)
  File "/home/ubuntu/anaconda3/envs/deeplab2/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ubuntu/anaconda3/envs/deeplab2/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/build_step_data.py", line 294, in main
    FLAGS.use_two_frames)
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/build_step_data.py", line 283, in _convert_dataset
    use_two_frames, is_testing)
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/build_step_data.py", line 247, in _create_panoptic_tfexample
    prev_label_data=prev_label_data)
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/data_utils.py", line 224, in create_video_tfexample
    label_format)
  File "/home/ubuntu/yunjian/motion_deeplab/deeplab2/data/data_utils.py", line 124, in create_features
    raise ValueError('Unsupported image format: %s' % image_format)
ValueError: Unsupported image format: jpg

Process finished with exit code 1

following the guide:https://github.com/google-research/deeplab2/blob/main/g3doc/setup/kitti_step.md, I transfer the KITTI dataset to KITTI_STEP, while I transfer MOT-Challenge following the guide:https://github.com/google-research/deeplab2/blob/main/g3doc/setup/motchallenge_step.md, I get the above error.

**Comment by ClaireXie** [comment]
Hi yjlin0223,

Thanks for pointing out this issue. We fixed this last week in https://github.com/google-research/deeplab2/commit/a58814f71e00092ddda9d913ae91e653a0b5da28#diff-9ab724a923b0af2a9aa0ff05336efb87037db7fee59123ade73e24efc0a0aec6. Can you update your branch to incorporate this change?

**Comment by yjlin0223** [comment]
thanks,it works
