### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS error when running cityscapes training

### ISSUE THREAD

**Issue by mi2celis** [google-research/deeplab2#40]
I am trying to run the cityscapes training with the information provided. Prepared the data as indicated.
Using resnet50_beta_os32.textproto with cityscapes_panoptic.

tensorflow              2.5.0
tensorflow-gpu       2.5.0
NVIDIA-SMI 460.84
CUDA Version: 11.2
cuDNN version 8.1.01GeForce RTX 2080  (10MiB / 11019MiB)

I changed the batch size from 32 to 8 in case I was running out of memory, but I got the same error
**CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered**

Any suggestions?

_Commad:_
`python trainer/train.py \
    --config_file="configs/cityscapes/panoptic_deeplab/resnet50_beta_os32.textproto"\
    --mode=train \
    --model_dir="output" \
    --num_gpus=1`

_Output:_
....
2021-07-28 12:18:26.707841: I tensorflow/core/common_runtime/bfc_allocator.cc:1066] Stats: 
Limit:                     10117644288
InUse:                      9929398016
MaxInUse:                   9995489536
NumAllocs:                        1320
MaxAllocSize:               2153779200
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-07-28 12:18:26.707916: W tensorflow/core/common_runtime/bfc_allocator.cc:467] ***************************************************************************************************_
2021-07-28 12:18:26.707968: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops.cc:662 : Resource exhausted: OOM when allocating tensor with shape[8,256,257,513] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
restoring or initializing model...
restored model from /home/mimi/code/deeplab2_proj/deeplab2/output/CITY_PANOPTIC_EXAMPLE/ckpt-0.
restored from checkpoint: /home/mimi/code/deeplab2_proj/deeplab2/output/CITY_PANOPTIC_EXAMPLE/ckpt-0
train | step:      0 | training until step 60000...
Traceback (most recent call last):
  File "trainer/train.py", line 81, in <module>
    app.run(main)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 77, in main
    FLAGS.num_gpus)
  File "/home/mimi/code/deeplab2_proj/deeplab2/trainer/train_lib.py", line 191, in run_experiment
    steps=config.trainer_options.solver_options.training_number_of_steps)
  File "/home/mimi/code/deeplab2_proj/deeplab2/models/orbit/controller.py", line 240, in train
    self._train_n_steps(num_steps)
  File "/home/mimi/code/deeplab2_proj/deeplab2/models/orbit/controller.py", line 439, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/home/mimi/code/deeplab2_proj/deeplab2/models/orbit/standard_runner.py", line 146, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted:  OOM when allocating tensor with shape[8,64,513,1025] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node while/body/_1/DeepLab/resnet50_beta/stage2/block1/conv1_bn_act/conv/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[while/merge/_973/_13]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted:  OOM when allocating tensor with shape[8,64,513,1025] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node while/body/_1/DeepLab/resnet50_beta/stage2/block1/conv1_bn_act/conv/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored. [Op:__inference_loop_fn_46399]

Function call stack:
loop_fn -> loop_fn

**2021-07-28 12:18:28.097617: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2021-07-28 12:18:28.097660: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1**
Fatal Python error: Aborted

Thread 0x00007f85d6c43740 (most recent call first):
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1264 in delete_iterator
  File "/home/mimi/Envs/deeplab2/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 546 in __del__

**Comment by aquariusjay** [comment]
If it is related to GPU memory, maybe take a look at [FAQ](https://github.com/google-research/deeplab2/blob/main/g3doc/faq.md).

For example, you could use crop size 513x1025 and batch size 1 and see if it trains.
If it works, you could then gradually increase the batch size and crop size.

**Comment by mi2celis** [comment]
Your suggestions solved the issue. Thank you.
