### ISSUE TITLE
Some question about the eval codes on on Cityscapes test datasets?

### ISSUE THREAD

**Issue by pingjun18-li** [google-research/deeplab2#55]
Hello, thank you for you codes,firstly.
Now I want to use this code(axial_deeplab) to generate panoptic segmentation results on unlabeled data such as test set, and then generate test tfRecord, but when I use the following command to test, 

> python trainer/train.py     --config_file="/home/sr6/yi0813.zhou/pingjun/deeplab2/configs/cityscapes/axial_deeplab/axial_swidernet_1_1_4.5_os16.textproto"     --mode='eval'     --model_dir="/home/sr6/yi0813.zhou/pingjun/deeplab2/init_checkpoints/axial_swidernet_1_1_4_5/" `--num_gpus=1`

**I get the following error:**
`- ***** TopKCrossEntropyLoss, gt_key: semantic_gt, pred_key: semantic_logits, weight_key: semantic_loss_weight, self._dynamic_weight: False
****** TopKCrossEntropyLoss, gt: (1, 1025, 2049, 19), pred: (1, 1025, 2049, 19), weights: (1, 1025, 2049), _top_k_percent_pixels: 0.20000000298023224
2021-09-16 17:29:34.622250: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
2021-09-16 17:29:34.624420: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
Traceback (most recent call last):
  File "trainer/train.py", line 83, in <module>
2021-09-16 17:29:34.625410: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
2021-09-16 17:29:34.626488: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
    app.run(main)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/absl/app.py", line 312, in run
2021-09-16 17:29:34.627536: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
2021-09-16 17:29:34.628701: W tensorflow/core/framework/op_kernel.cc:1692] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: image/segmentation/class/encoded (data type: string) is required but could not be found.
`
So I think the prediction process for unlabel data shouldn't use this command, could you guide me or provide the correct test code? 
Someone have same question or have solved ? thank you teach.

Thank you again!

**Comment by aquariusjay** [comment]
Hi @pingjun18-li,

Based on the provided error log, it seems that the code tries to read the segmentation groundtruth but they are not provided. Since you would like to generate panoptic segmentation results on unlabeled data such as test set, maybe you could take a look at this [tutorial](https://github.com/google-research/deeplab2/blob/main/g3doc/setup/cityscapes_test_server_evaluation.md#save-raw-panoptic-prediction).

Cheers,

**Comment by pingjun18-li** [comment]
Thank you for your prompt reply!
I have tried the tutorial and setted the textproto as below:
`evaluator_options {
  continuous_eval_timeout: -1
  stuff_area_limit: 2048
  center_score_threshold: 0.1
  nms_kernel: 13
  save_predictions: true
  save_raw_predictions: true
  convert_raw_to_eval_ids: true
  decode_groundtruth_label: false
  merge_semantic_and_instance_with_tf_op: false`

**but still have the error**
`I0917 11:07:02.452849 47433365885120 train.py:71] Reading the config file.
Traceback (most recent call last):
  File "trainer/train.py", line 83, in <module>
    app.run(main)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 73, in main
    config = text_format.ParseLines(proto_file, config_pb2.ExperimentOptions())
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 771, in ParseLines
    return parser.ParseLines(lines, message)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 824, in ParseLines
    self._ParseOrMerge(lines, message)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 852, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 982, in _MergeField
    merger(tokenizer, message, field)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 1057, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/sr6/yi0813.zhou/pingjun/python3.7.3/python3.7.3/lib/python3.7/site-packages/google/protobuf/text_format.py", line 949, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 158:3 : Message type "deeplab2.EvaluatorOptions" has no field named "decode_groundtruth_label".`

So what can i do ?

Best regards

**Comment by pingjun18-li** [comment]
Thank you for the guidance! it's working now.
and one more question, i want to use this project to generate high quality pseudo label on the unlabel data, is this project support multi-scales test? or which config options  I should change for that?

Best regards!

**Comment by aquariusjay** [comment]
Hi @pingjun18-li,

We currently only support multi-scale test for Panoptic-DeepLab.
You could specify the [eval_scales](https://github.com/google-research/deeplab2/blob/e4c86be825b3f87f2ed6b84bb56b84a4b6d579cb/evaluator.proto#L84) and [left-right flips](https://github.com/google-research/deeplab2/blob/e4c86be825b3f87f2ed6b84bb56b84a4b6d579cb/evaluator.proto#L81).
[Here](https://github.com/google-research/deeplab2/blob/main/model/deeplab.py#L146) is the link to the place where multi-scale inference is performed.

Cheers,

**Comment by pingjun18-li** [comment]
Ok，I know the multi-scale test for Panoptic-DeepLab, which is add by me and changed by bowen for troch version^_^,
thank you again, i will try the multi-scale by myself.
Best regards!

**Comment by aquariusjay** [comment]
Closing the issue since it is not active for a while.
Please feel free to reopen it if needed.
