### ISSUE TITLE
Possible MaX-DeepLab-L-Backbone ImageNet checkpoint issue

### ISSUE THREAD

**Issue by louisquinn** [google-research/deeplab2#60]
Hey guys, 

Possible issue with the supplied Max-DeepLab-L backbone Imagenet checkpoint. 

On a working Max-DL-S config, I swapped out the following to attempt a Max-DL-L train:

```
name: "max_deeplab_l"
initial_checkpoint: "max_deeplab_l_backbone_imagenet1k_strong_training_strategy/ckpt-350"
```

And got the following error: (I think this checkpoint is actually from a specific dataset?)

```
ValueError: The initial value's shape ((1, 1, 2048, 512)) is not compatible with the explicitly supplied `shape` argument ((1, 1, 2048, 1024)).
```

Full stack trace below:
```
I0923 13:32:21.470141 140322436347712 api.py:446] Eval with scales ListWrapper([1.0])
I0923 13:32:22.874432 140322436347712 api.py:446] Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.
I0923 13:32:22.898995 140322436347712 api.py:446] Eval scale 1.0; setting pooling size to [21, 21]
Traceback (most recent call last):
  File "trainer/train.py", line 80, in <module>
    app.run(main)
  File "ai-env-deeplab2/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "ai-env-deeplab2/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "trainer/train.py", line 76, in main
    FLAGS.num_gpus)
  File "deeplab2/trainer/train_lib.py", line 210, in run_experiment
    build_deeplab_model(deeplab_model, crop_size)
  File "deeplab2/trainer/train_lib.py", line 76, in build_deeplab_model
    tf.keras.Input(input_shape, batch_size=batch_size), training=False)
  File "ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    deeplab2/model/deeplab.py:159 call  *
        pred_dict = self._decoder(
    deeplab2/model/encoder/axial_resnet.py:763 call  *
        memory_feature, high_resolution_outputs, backbone_output, endpoints = (
    deeplab2/model/encoder/axial_resnet.py:665 call_stacked_decoder  *
        activated_output = getattr(self, current_name)(
    deeplab2/model/layers/resized_fuse.py:154 call  *
        feature = getattr(self, current_name)(feature, training=training)
    deeplab2/model/layers/convolutions.py:287 call  *
        x = self._conv(x)
    ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py:1030 __call__  **
        self._maybe_build(inputs)
    ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py:2659 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    ai-env-deeplab2/lib/python3.6/site-packages/keras/layers/convolutional.py:204 build
        dtype=self.dtype)
    ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer.py:663 add_weight
        caching_device=caching_device)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py:818 _add_variable_with_custom_getter
        **kwargs_for_getter)
    ai-env-deeplab2/lib/python3.6/site-packages/keras/engine/base_layer_utils.py:129 make_variable
        shape=variable_shape if variable_shape else None)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:266 __call__
        return cls._variable_v1_call(*args, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:227 _variable_v1_call
        shape=shape)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2127 creator_with_resource_vars
        created = self._create_variable(next_creator, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py:530 _create_variable
        distribute_utils.VARIABLE_POLICY_MAPPING, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_utils.py:308 create_mirrored_variable
        value_list = real_mirrored_creator(**kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/distribute/mirrored_strategy.py:522 _real_mirrored_creator
        v = next_creator(**kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:205 <lambda>
        previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py:2626 default_variable_creator
        shape=sha/var/sensen/ai/pe)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/variables.py:270 __call__
        return super(VariableMetaclass, cls).__call__(*args, **kwargs)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1613 __init__
        distribute_strategy=distribute_strategy)
    ai-env-deeplab2/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1753 _init_from_args
        (initial_value.shape, shape))
​
    ValueError: The initial value's shape ((1, 1, 2048, 512)) is not compatible with the explicitly supplied `shape` argument ((1, 1, 2048, 1024)).
```

**Comment by louisquinn** [comment]
Hey @aquariusjay sorry for the late reply!

So I am able to confirm that the COCO config works **only for:**
```
output_stride: 16
atrous_rates: [6, 12, 18]
```

It crashes with the same error for:
```
output_stride: 32
atrous_rates: [3, 6, 9]
```
and
```
output_stride: 8
atrous_rates: [12, 24, 36]
```

I'm unsure if this is intentional but either way its fine with us for now! However in the future we may need to use varying values.

**Comment by aquariusjay** [comment]
Hi @louisquinn,

MaX-DeepLab's architecture is not flexible in the sense that we could change output_stride to any value you like.
Please use the same setting as specified by the provided config.
Closing the issue, but please feel free to reopen it if needed.

Cheers,
