### ISSUE TITLE
Semantic segmentation with mobilenetv3 + deeplabv3

### ISSUE THREAD

**Issue by hjonnala** [google-research/deeplab2#79]
Hi,

### Our Objective is  to develop a full quant model to map it to coral Edge TPU

I am trying to train the semantic segmentation model with mobilenet v3 and deeplabv3 with cityscapes dataset.

For this I have changed [panoptic deeplab](https://github.com/google-research/deeplab2/blob/main/configs/cityscapes/panoptic_deeplab/mobilenet_v3_small_os16.textproto#L45) with [deeplab v3](https://github.com/google-research/deeplab2/blob/main/configs/example/example_cityscapes_deeplabv3.textproto#L17). But I am getting into issues with trainer options. Can someone please provide me the config file for training the mobilentv3 model with deeplab v3. Thanks!

cmd:
python trainer/train.py     --config_file='/Users/hemanth/deeplab_edge/deeplab2/configs/cityscapes/panoptic_deeplab/mobilenet_v3_small_os16.textproto'     --mode=train     --model_dir='/Users/hemanth/deeplab_edge/mobilenetv3small'

Error log:

Traceback (most recent call last):
  File "/Users/hemanth/deeplab_edge/deeplab2/trainer/train.py", line 76, in <module>
    app.run(main)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/Users/hemanth/deeplab_edge/deeplab2/trainer/train.py", line 71, in main
    train_lib.run_experiment(FLAGS.mode, config, combined_model_dir, FLAGS.master,
  File "/Users/hemanth/deeplab_edge/deeplab2/trainer/train_lib.py", line 190, in run_experiment
    controller.train(
  File "/Users/hemanth/deeplab_edge/models/orbit/controller.py", line 240, in train
    self._train_n_steps(num_steps)
  File "/Users/hemanth/deeplab_edge/models/orbit/controller.py", line 442, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/Users/hemanth/deeplab_edge/models/orbit/standard_runner.py", line 146, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/hemanth/deeplab_env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    /Users/hemanth/deeplab_edge/models/orbit/utils/loop_fns.py:120 loop_fn  *
        step_fn(iterator)
    /Users/hemanth/deeplab_edge/deeplab2/trainer/trainer.py:218 step_fn  *
        self._train_step(inputs)
    /Users/hemanth/deeplab_edge/deeplab2/trainer/trainer.py:236 _train_step  *
        loss_dict = self._loss(inputs, outputs)
    /Users/hemanth/deeplab_edge/deeplab2/model/loss/loss_builder.py:214 call  *
        loss_value = loss_func(y_true, y_pred)
    /Users/hemanth/deeplab_edge/deeplab2/model/loss/base_loss.py:287 call  *
        gt = y_true[self._gt_key]

    KeyError: 'instance_center_gt'

y_true : {'image': <tf.Tensor 'IteratorGetNext:0' shape=(64, 1025, 2049, 3) dtype=float32>, 'semantic_gt': <tf.Tensor 'IteratorGetNext:2' shape=(64, 1025, 2049) dtype=int32>, 'semantic_loss_weight': <tf.Tensor 'IteratorGetNext:3' shape=(64, 1025, 2049) dtype=float32>, 'is_crowd_gt': <tf.Tensor 'IteratorGetNext:1' shape=(64, 1025, 2049) dtype=bool>}

**Comment by aquariusjay** [comment]
Hi @hjonnala,

You may be able to modify this semantic-segmentation-only [config](https://github.com/google-research/deeplab2/blob/main/configs/cityscapes/panoptic_deeplab/resnet50_os32_semseg.textproto) for your use case.

Cheers,

**Comment by hjonnala** [comment]
> Hi @hjonnala,
> 
> You may be able to modify this semantic-segmentation-only [config](https://github.com/google-research/deeplab2/blob/main/configs/cityscapes/panoptic_deeplab/resnet50_os32_semseg.textproto) for your use case.
> 
> Cheers,

@aquariusjay it works. Thanks!
