### ISSUE TITLE
'SwitchableAtrousConvolution' object has no attribute 'convolution_op'

### ISSUE THREAD

**Issue by Shaiken** [google-research/deeplab2#87]
i git checkout SHA-1: 77163c7578e1b3352d04cd9daaf8e8462a18c174
use nvidia container tensorflow:21.06-tf2-py3/tensorflow:21.09-tf2-py3/tensorflow:21.11-tf2-py3
ubuntu: 18.04.6
gpu: v100
cuda: 11.4

run docker command:
docker run --gpus all --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v/opt/Shaiken:/code nvcr.io/nvidia/tensorflow:21.06-tf2-py3, or other images

i try run Panoptic-DeepLab(SWideRNet-SAC-(1, 1, 4.5))

swidernet_sac_1_1_4.5_os16.textproto:

//# Use a unique experiment_name for each experiment.
experiment_name: "shaiken"
model_options {
  initial_checkpoint: "deeplab2/swidernet_sac_1_1_4.5_os16/ckpt-60000"
...

train_dataset_options {
  dataset: "cityscapes_panoptic"
  //# Update the path to training set.
  file_pattern: "/code/test/deeplab2/data/cityscapes/tfrecord/train*.tfrecord"
  //# Adjust the batch_size accordingly to better fit your GPU/TPU memory.
  //# Also see Q1 in g3doc/faq.md.
  batch_size: 1
  crop_size: 577
  crop_size: 1025
...

eval_dataset_options {
  dataset: "cityscapes_panoptic"
  //# Update the path to validation set.
  file_pattern: "/code/test/deeplab2/data/cityscapes/tfrecord/val*.tfrecord"
  batch_size: 1
  crop_size: 577
  crop_size: 1025

-----
something i don't understand error when run train.py:

first error:
2022-03-08 10:04:03.906271: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0308 10:04:10.911404 140278983419712 train.py:65] Reading the config file.
I0308 10:04:10.914586 140278983419712 train.py:69] Starting the experiment.
2022-03-08 10:04:10.934482: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-03-08 10:04:10.943546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1034] **successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero**

second error:
I0308 10:04:19.133949 140278983419712 deeplab.py:96] Setting pooling size to (37, 65)
I0308 10:04:19.134186 140278983419712 aspp.py:135] **Global average pooling in the ASPP pooling layer was replaced with tiled average pooling using the provided pool_size. Please make sure this behavior is intended.**

last error:
Traceback (most recent call last):
  File "deeplab2/trainer/train.py", line 76, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab2/trainer/train.py", line 71, in main
    train_lib.run_experiment(FLAGS.mode, config, combined_model_dir, FLAGS.master,
  File "/code/test/deeplab2/trainer/train_lib.py", line 187, in run_experiment
    build_deeplab_model(deeplab_model, crop_size)
  File "/code/test/deeplab2/trainer/train_lib.py", line 75, in build_deeplab_model
    deeplab_model(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 969, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1107, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 840, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 880, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /code/test/deeplab2/model/deeplab.py:155 call  *
        pred_dict = self._decoder(
    /code/test/deeplab2/model/encoder/axial_resnet.py:761 call  *
        current_output, activated_output, memory_feature, endpoints = (
    /code/test/deeplab2/model/encoder/axial_resnet.py:560 call_encoder_before_stacked_decoder  *
        current_output, activated_output, memory_feature = (
    /code/test/deeplab2/model/layers/axial_block_groups.py:374 call  *
        _ = block_fn_no_recompute(tuple(block_fn_inputs))
    /code/test/deeplab2/model/layers/axial_blocks.py:293 call  *
        x = self._conv2_bn_act(x, training=training)
    /code/test/deeplab2/model/layers/convolutions.py:287 call  *
        x = self._conv(x)
    /code/test/deeplab2/model/layers/convolutions.py:114 call  *
        outputs = self.convolution_op(inputs, self.kernel)

    **AttributeError: 'SwitchableAtrousConvolution' object has no attribute 'convolution_op'**

---

**Comment by aquariusjay** [comment]
Hi @Shaiken,

Thank you for reporting the issue.
TF Keras recently changed the api for convolution_op (from [self._convolution_op](https://github.com/keras-team/keras/blob/v2.6.0/keras/layers/convolutional.py#L234) to [self.convolution_op](https://github.com/keras-team/keras/blob/v2.8.0/keras/layers/convolutional.py#L225)).
Please make sure the Keras version you are using uses self.convolution_op.
(or you can modify the code in a similar manner as self._convolution_op code in the previous Keras version).

Cheers,

**Comment by Shaiken** [comment]
may i ask other question, i got another question...
 ---
I0311 05:57:32.617569 139685618747200 controller.py:236] train | step:      0 | training until step 60000...
train | step:      0 | training until step 60000...
2022-03-11 05:57:32.978885: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Traceback (most recent call last):
  File "deeplab2/trainer/train.py", line 76, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab2/trainer/train.py", line 71, in main
    train_lib.run_experiment(FLAGS.mode, config, combined_model_dir, FLAGS.master,
  File "/code/test/deeplab2/trainer/train_lib.py", line 190, in run_experiment
    controller.train(
  File "/code/test/models/orbit/controller.py", line 240, in train
    self._train_n_steps(num_steps)
  File "/code/test/models/orbit/controller.py", line 439, in _train_n_steps
    train_output = self.trainer.train(num_steps_tensor)
  File "/code/test/models/orbit/standard_runner.py", line 146, in train
    self._train_loop_fn(self._train_iter, num_steps)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Input to DecodeRaw has length 8529 that is not a multiple of 4, the size of int32
         [[{{node DecodeRaw}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[while/body/_1/IteratorGetNext]]
         [[Func/while/body/_1/output_control_node/_9337/_119]]
  (1) Invalid argument:  Input to DecodeRaw has length 8529 that is not a multiple of 4, the size of int32
         [[{{node DecodeRaw}}]]
         [[MultiDeviceIteratorGetNextFromShard]]
         [[RemoteCall]]
         [[while/body/_1/IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_loop_fn_139581]

Function call stack:
loop_fn -> loop_fn
