### ISSUE TITLE
Cannot handle this data type: (1, 1, 9), |u1

### ISSUE THREAD

**Issue by Shaiken** [google-research/deeplab2#89]
Sorry ask about this question..!

i try use custom map png to call create_step_panoptic_maps.py
the png structure is background(0,0,0) and target(1,1,1), 
and edit create_step_panoptic_maps.py

---
```
  #--------------------------------------------------------------
  # Original index | Updated index|   Note
  #----------------+--------------+------------------------------
  #       0        |     255      |   void value
  #       1        |      1       |   keep target

```
and folder about sequence_id, i ignore this.
so ..root directory structure

+ INPUT_SEMANTIC_MAP_ROOT_DIR
  + train
      - *.png
      ...
  + val
---
i print every png shape:

semantic_map (768, 1024, 3)
instance_map (768, 1024, 3)
panoptic_map (768, 1024, 3)
**encode_panoptic_map_unfromarray (768, 1024, 9)** 
---
and run command 
python deeplab2/data/utils/create_step_panoptic_maps.py --input_semantic_map_root_dir=/code/test/deeplab2/data/cityscapes/mask/ --input_instance_root_dir=/code/test/deeplab2/data/cityscapes/mask/ --output_panoptic_map_root_dir=/code/test/deeplab2/data/cityscapes/mask_new/

**the semantic_map and input_instance_root_dir pngs are same**
but seem had a strange error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2835, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 9), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "deeplab2/data/utils/create_step_panoptic_maps.py", line 393, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "deeplab2/data/utils/create_step_panoptic_maps.py", line 387, in main
    panoptic_map_generator.build_panoptic_maps(
  File "deeplab2/data/utils/create_step_panoptic_maps.py", line 339, in build_panoptic_maps
    encoded_panoptic_map = Image.fromarray(encode_panoptic_map(panoptic_map)).convert('RGB')
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2837, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1, 9), |u1
```

**Comment by Shaiken** [comment]
> Sorry ask about this question..!
> 
> i try use custom map png to call create_step_panoptic_maps.py the png structure is background(0,0,0) and target(1,1,1), and edit create_step_panoptic_maps.py
> 
> ```
>   #--------------------------------------------------------------
>   # Original index | Updated index|   Note
>   #----------------+--------------+------------------------------
>   #       0        |     255      |   void value
>   #       1        |      1       |   keep target
> ```
> 
> and folder about sequence_id, i ignore this. so ..root directory structure
> 
> * INPUT_SEMANTIC_MAP_ROOT_DIR
>   
>   * train
>     
>     * *.png
>       ...
>   * val
> 
> i print every png shape:
> 
> ## semantic_map (768, 1024, 3)
> instance_map (768, 1024, 3)
> panoptic_map (768, 1024, 3)
> **encode_panoptic_map_unfromarray (768, 1024, 9)**
> and run command python deeplab2/data/utils/create_step_panoptic_maps.py --input_semantic_map_root_dir=/code/test/deeplab2/data/cityscapes/mask/ --input_instance_root_dir=/code/test/deeplab2/data/cityscapes/mask/ --output_panoptic_map_root_dir=/code/test/deeplab2/data/cityscapes/mask_new/
> 
> **the semantic_map and input_instance_root_dir pngs are same** but seem had a strange error.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2835, in fromarray
>     mode, rawmode = _fromarray_typemap[typekey]
> KeyError: ((1, 1, 9), '|u1')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "deeplab2/data/utils/create_step_panoptic_maps.py", line 393, in <module>
>     app.run(main)
>   File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "deeplab2/data/utils/create_step_panoptic_maps.py", line 387, in main
>     panoptic_map_generator.build_panoptic_maps(
>   File "deeplab2/data/utils/create_step_panoptic_maps.py", line 339, in build_panoptic_maps
>     encoded_panoptic_map = Image.fromarray(encode_panoptic_map(panoptic_map)).convert('RGB')
>   File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 2837, in fromarray
>     raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
> TypeError: Cannot handle this data type: (1, 1, 9), |u1
> ```
